### ISSUE TITLE
Limit RAM usage

### ISSUE THREAD

**Issue by vbmithr** [segmentio/parquet-go#118] opened 2022-03-29 13:41 UTC
I’m trying to use `flush` on the writer to limit RAM usage, but it seems to have no effect.
It seems that buffers are never cleared during the execution of the program, as if all the data I ever write is kept in memory. Not sure what to do here.

Best,

**Comment by vbmithr** [comment] 2022-03-31 16:57
I guess it is because it tries to put all data in one row group. I have looked at the WriteRowgroup function but it seems overkill to have to reimplement a lot just to avoid using all RAM.
Is there ways to setup the maximum number of values per row group so that row groups are created on demand (and memory freed in between row groups?).
I also looked at column buffers to use swap, but really, what I’d like is to write the file so that not much memory is consumed while doing it, not having to swap a lot of data.
Probably I don’t understand something but I haven’t yet figured out.

Best

**Comment by achille-roussel** [comment] 2022-04-08 21:17
Hello @vbmithr, thanks for reaching out!

I've added documentation in https://github.com/segmentio/parquet-go/pull/130 which describes how to use on-disk page buffers to avoid consuming large amount of memory when writing large row groups, this might be useful to your use case.

Calling `Flush` on a writer should materialize a row group in the file as well, if memory isn't released or reused in this case it might be a bug. Could you share a code snippet reproducing the issue you reported?

Let me know if that helps.

**Comment by vbmithr** [comment] 2022-04-16 09:34
Thanks Achille, I have just sent you a mail with details on how to reproduce.

**Comment by achille-roussel** [comment] 2022-04-16 19:55
Thanks for sending the code snippet to reproduce the issue.

I took a look and I think parquet-go and your program behave as expected here, there is not memory leak.

If I'm understanding correctly, the high memory usage is combination of two factors:
* your program dynamically create writers, one for each dimension that you are generating a parquet file for
* the default configuration for a `parquet.Writer` is to allocate 1 MiB buffers for each column

The schema you are using has 5 rows, so each writer uses 5 MiB of memory. I ran the program on a subset of your example input (10% of the rows), which results in generating 183 files, 5 x 183 = ~900 MiB, which is also the heap footprint that I was able to measure by modifying your program to generate a memory profile.

Here is a capture of the memory profile, showing that memory is being allocated in 1 MiB blocks in the column buffers used by the writer:

![image](https://user-images.githubusercontent.com/865510/163689548-82e0eb59-613e-4df6-b01b-e92841adc235.png)

It appeared the parquet files you generated end up being pretty small, so these 1 MiB column buffers go mostly unused. I set the [PageBufferSize](https://pkg.go.dev/github.com/segmentio/parquet-go#PageBufferSize) configuration option to 64 KiB to reduce the memory footprint of each writer, which appeared to greatly reduce the memory footprint used by the column buffers. Here is a highlight of comparing the memory profiles before an after the configuration change:

![image](https://user-images.githubusercontent.com/865510/163689537-b063fd34-76ee-490e-8bd0-c22e635e2543.png)

**Comment by vbmithr** [comment] 2022-04-18 09:46
I have reproduced the memory trace. Indeed, these report very little memory usage, but in practice my program still allocates (and needs!) 5GiB of RAM to run correctly. I can understand why it consumes at least 2GiB for loading the JSON file into memory but I don’t know where the last 3GiB comes from. Thanks for your help, anyway!

**Comment by achille-roussel** [comment] 2022-04-18 21:00
Unless I'm missing something, parquet-go is behaving as intended here and offers the ability to tune memory utilization to better suit your use case.

I'm closing the issue, feel free to reopen if you think further changes or discussions are needed.

**Closed by achille-roussel** 2022-04-18 21:00 UTC
Labels: question

**Comment by vbmithr** [comment] 2022-04-19 14:21
`GOGC` did wonders, eventually. Thanks for the help, @achille-roussel!
